[package]
name = "splash-server"
description = "A better webseite for the AfrA"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
base64 = "0.9.0"