CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  pw_hash VARCHAR NOT NULL,
  salt VARCHAR NOT NULL
);

CREATE TABLE sessions (
  id INTEGER NOT NULL PRIMARY KEY,
  token VARCHAR NOT NULL,
  user INTEGER NOT NULL,
  FOREIGN KEY (user) REFERENCES users(id)
);
